import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local';

const fontCausten = localFont({
  src: [
    {
      path: "../asset/fonts/Causten Medium.ttf",
      weight: '400',
      style:'normal'
    },
        {
      path: "../asset/fonts/Causten Bold.ttf",
      weight: '500',
      style:'bold'
    },
          {
      path: "../asset/fonts/Causten Regular.ttf",
      weight: '300',
      style:'bold'
    }
  ]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fontCausten.className}>
      <body>
        {children}
      </body>
    </html>
  );
}
