import type { Metadata } from "next";
import "./globals.css";

import localFont from "next/font/local";
import { Header } from "@/components/sections/header/header";

const fontCausten = localFont({
  src: [
    {
      path: "../public/fonts/Causten Medium.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Causten Bold.ttf",
      weight: "500",
      style: "bold",
    },
    {
      path: "../public/fonts/Causten Regular.ttf",
      weight: "300",
      style: "bold",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fontCausten.className}>
      <body>
        <header>
          <Header />
        </header>
        <main className="mt-[60px]! md:mt-[108px]! container mx-auto p-5">{children}</main>
      </body>
    </html>
  );
}
